config/routes.rb
Testprogram::Application.routes.draw do

  root to: "home#index"
  
  match 'becky', to: 'awesome#rockon'
  
  resources :people do
    collection do
      get :search
      post :search
    end
	resources :addresses, only: [:new, :create]
  end
  

 

end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :person_id, :street_name, presence: true
  
  belongs_to :person
  
  attr_accessible :street_name, :street_name_secondary, :city, :state_abbr, :zip, :zip_ext
end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :name1, :name2 
  
  has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
	def new
		@person = Person.find(params[:person_id])
		@address = @person.addresses.build
	end
	
	def create
		@person = Person.find(params[:person_id])
		@address = @person.addresses.build(params[:address])
		if @address.save 
			redirect_to @person, notice: "Woohoo added the hizzy"
		else
			render :new
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end
  
  # GET /people/search
  # GET /people/search.json
  def search
    if params[:q].present?
      @people = Person.where(["name1 LIKE ?", "%#{params[:q]}%"])
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # person /people
  # person /people.json
  def create
    @person = Person.new(params[:person])
    if @person.save
      redirect_to @person, notice: "Person was successfully created."
    else
      render :new
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])
    if @person.update_attributes(params[:person])
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy


  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/addresses/new.html.erb
<p id="notice"><%=notice %></p>

<h1> Let's add an address! </h1>

<%= form_for [@person, @address] do |f| %>
  <p><%= @address.errors.full_messages.to_sentence %>.</p>

  <p> 
    <%= f.label :street_name %>
	<%= f.text_field :street_name %>
  </p>
<p> 
    <%= f.label :street_name_secondary %>
	<%= f.text_field :street_name_secondary %>
  </p>
<p> 
    <%= f.label :city %>
	<%= f.text_field :city %>
  </p>
<p> 
    <%= f.label :state_abbr %>
	<%= f.text_field :state_abbr %>
  </p>
<p> 
    <%= f.label :zip %>
	<%= f.text_field :zip %>
  </p>
<p> 
    <%= f.label :zip_ext %>
	<%= f.text_field :zip_ext %>
  </p>
<p> 
	<%= f.button :submit %>
  </p>
  
<% end%>

app/views/home/index.html.erb
<h1>View, Edit, Create, Delete Names</h1>

<%= link_to "List All Names", people_path %>

<br> <br> <br>

<%= link_to "Search For Someone", search_people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testprogram</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<p id="notice"><%= notice %></p>

<h1>Let's make some changes!!</h1>


<p>
 <%=@person.name1%>'s id number is:
  <%= @person.ID%> (you can't change his ID number, though)
</p>

<%# this is an edit form (form_for @my_object [automatically has method :post])%>
<%= form_for @person do |f| %>
<p>
  <%= f.label :name1 %>
  <%= f.text_field :name1 %>
</p>
<p>
  <%= f.button 'Go' %>
  <!-- <button type="submit">Go</button> -->
</p>
<% end %>

<%= link_to 'search', search_people_path %>
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Name List</h1>



<table>
  <tr>
    <th>Name</th>
    <th> </th>
    <th>ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name1 %></td>
    <td><%= person.name2 %></td>
    <td><%= person.ID %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'search', search_people_path %>

<%= link_to 'New person', new_person_path %>

app/views/people/new.html.erb
<p id="notice"><%= notice %></p>

<h1>Yo! Let's add someone to the database!</h1>


<%= form_for :new, html: {method: 'get'} do |f| %>
<p>
  <%= f.label :q, "Enter a name (last, first, middle format, pretty please)." %>
  <%= f.text_field :q, name: :q, value: params[:q] %>
  <%= f.button 'Go' %>
</p>  


<% end %>


<%= link_to 'search', search_people_path %>
<%= link_to 'Back', people_path %>

app/views/people/search.html.erb
<p id="notice"><%= notice %></p>

<h1>Looking for someone</h1>

<%= form_for :search, html: {method: 'get'} do |f| %>
<p>
  <%= f.label :q, "Search by Name" %>
  <%= f.text_field :q, name: :q, value: params[:q] %>
  <%= f.button 'Go' %>
</p>  
<% end %>
<!-- comment for html -->
  
<%# comment for erb (source source) -%>  

<%- if @people.present? %>
  <table>
  <tr>
    <th>Name</th>
    <th> </th>
    <th>ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name1 %></td>
    <td><%= person.name2 %></td>
    <td><%= person.ID %></td>
    <td><%= link_to 'Show', Person %></td>
    <td><%= link_to 'Edit', edit_person_path(Person) %></td>
    <td><%= link_to 'Destroy', Person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<%- elsif params[:q].present? %>

<h2>There are no search results</h2>

<%- else %>

<h2>Everybody is looking for somebody... and the person you're looking for isn't in our database.</h2>
  <td><%= link_to 'Create', edit_person_path(Person) %></td>

<%- end %>
  
<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name1 %>
</p>

<p>
  <b>ID:</b>
  <%= @person.ID%>
</p>

<%- if @person.addresses.present? %>
	<ol>
		<%- @person.addresses.each do |address| %>
			<li> 
				<%= address.street_name %>
			</li>
		<%   end %>
	</ol>
<%  end %>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Add address', new_person_address_path(@person) %> |
<%= link_to 'Back', people_path %>